after_script:
- bash <(curl -s https://codecov.io/bash)
dotnet: 2.2.1
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: csharp
mono: none
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: rVoi5XXXyFfMXb5Byzlh6yXQq+4pY76DumL5W11X11OZ/dJAOHgrBD8oCYSiKcmvYppmSYTxzBJSWVs85kdtWJbVD4hnN5xYY0jllN1sg/ajo0p90Qw7++4q0tF3BnH73Hib6HFBkHS8YPlxzt3lXo52vn9IzMFo0MVWCAsJbPKSfcFXntHUM3Nwqi0j4yZHa1eU/pi9iN3I5BLSp7AHnbR1QJy3isdEvrICBml/uVZl3C5h0I1//ZM1dcorBz0VJg6g30gKj2dkmcP8Qooa9edpwhye+a0wUvIkPYlwXOiAUr6OQCT4ioJ446Zxn3i4UpMfKjOwBbgf6vd5V5jviMejEcxu2HeU8DldeUqsw6sVEx0W/XfSjVZgCLWmyMiMcMM19BQ19h0b1qVX4ODmY7oF9CAzyk3jBcvCwIqbizmcYUAZ+GUfEvv/vpWZHae2m/xXO72U4Mnna5QvmmdTQa5QoXDrQokEfhGNXrVzmb8LclKsl0RAO5xxWaZdKCVQocBdqKWSfrG4Y9EwiBjvuh2LsiG+kmvlz6uY05w5S0UISfzufzUBVg0Ghs4LqOmzusibolwYU6knlsXqpBoPuZAxEivX/K/Rt4wsu1E0/6MR8LA6mbRWKrXdGgcS/uWQlM6GdRJnc39PHWIEiPYxFUY9EBYfjNrvPnwnbRPSW40=
script:
- dotnet restore
- dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=90
solution: All.sln
